### ISSUE TITLE
BankID app does not return to Safari on iOS

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#156]
When using Safari on iOS the BankID app is started automatically, but I have to manually return back to Safari ...

**Comment by felix-hellman** [comment]
If the bug concerns an unexpected behaviour during a BankID operation include:

Device: Android/iOS/Windows/macOS
Browser: Safari/Chrome/Edge/Samsung Internet/...
BankID Device: Same/Other
User-Agent String: eg. Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by martin-lindstrom** [comment]
- Device: iOS
- Broswer: Safari
- BankID Device: Same
- User-Agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1`
