### ISSUE TITLE
Auth at mobile device - selecting Retry after time out does not open BankID app directly

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/bankid-saml-idp#177]
Initiate Authentication at mobile device but let the session time out by not submitting a password/touch id in the bankID app. After session time out, a page is presented to the user where it can select Retry or Abort.
If selecting Retry then the BankID app does not start automatically until about 30 seconds later.

**Comment by felix-hellman** [comment]
Please fill out the following information about this bug to allow us to replicate the issue.

Device: Android/iOS/Windows/macOS
Browser: Safari/Chrome/Edge/Samsung Internet/...
BankID Device: Same/Other
User-Agent String: eg. Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by ovesemart** [comment]
Device : iPad , iOS 16.6.1
Browser: Safari
BankID: same
User agent string: 
Mozilla/5.0 (iPad; CPU OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/188
