### ISSUE TITLE
Wrong text when using BankID on desktop

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#194]
When selecting "BankID on same device" on desktop the text "Start the BankID app and scan the QR code" is displayed. There is no QR-code involved here, so we are using the wrong text message here...

<img width="1243" alt="Screenshot 2023-10-17 at 18 39 18" src="https://github.com/swedenconnect/bankid-saml-idp/assets/18271099/c3679f9c-f70f-407f-8228-0a6250c3a056">

**Comment by oestrogen** [comment]
As said elsewhere: The wrong message code is sent from the backend.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/198
