### ISSUE TITLE
BankID on mobile device - stop polling for response when information dialogue is closed

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/bankid-saml-idp#196]
BankID on mobile device - stops polling for response when information dialogue is closed. See picture. 
Page will only update if one of the Device selection buttons are clicked.

<img width="758" alt="Skärmavbild 2023-10-18 kl  14 58 29" src="https://github.com/swedenconnect/bankid-saml-idp/assets/36661180/a4b956e3-26e3-4aad-9044-64bd5926b6a1">

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/197
