### ISSUE TITLE
BankID on mobile device is preselected for Signing when Identification was done with BankID on this device

### ISSUE THREAD

**Issue by ovesemart** [swedenconnect/bankid-saml-idp#200]
Precondition: A user first selects 'BankID on mobile device', closes the QR-code and then selects 'BankID on this device' and completes the authentication. 
If user then initiate a Sign flow, 'BankID on mobile device' is preselected and the QR-code is presented for the user. 'BankID on this device' should be preselected for the Signature flow in this case.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/201.
