### ISSUE TITLE
Problem running TLS with clustered redis

### ISSUE THREAD

**Issue by mikaelfrykholm** [swedenconnect/bankid-saml-idp#205]
Hi, We have a configuration like 
``` data:
    redis:
      cluster:
        nodes:
          - bankid-idp-redis3.qa.swamid.se:6379
          - bankid-idp-redis1.qa.swamid.se:6379
          - bankid-idp-redis2.qa.swamid.se:6379
      ssl:
        enabled: true
      ssl-ext:
        #enable-hostname-verification: true
        credential:
          resource: file://etc/ssl/private/bankid-idp-app2.qa.swamid.se_infra.p12
          password: qwerty123
        trust:
          resource: file://etc/ssl/private/bankid-idp-app2.qa.swamid.se_infra.p12
          password: qwerty123
```
and fail with:
```Oct 30 14:12:42 bankid-idp-app2 sunet-bankidp[3783546]: app_1    | 2023-10-30T15:12:42.476+01:00 ERROR 1 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'lockingFilter' defined in file [/app/classes/se/swedenconnect/bankid/idp/concurrency/LockingFilter.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'repository' defined in class path resource [se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.class]: Unsatisfied dependency expressed through method 'repository' parameter 0: Error creating bean with name 'redisson' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception with message: cluster servers config already used!```

My guess is that https://github.com/swedenconnect/bankid-saml-idp/blob/b1f48df46911fab2c9ce290221aea48838bf29c5/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java#L72 will need to understand clustered redis. 
What do you think?

Also spring ssl bundles would help here as well. :)

**Comment by felix-hellman** [comment]
You are probably correct. I don't have the time to test the fix for clustered but I will provide a branch/commit with something that should work.

https://github.com/swedenconnect/bankid-saml-idp/tree/bugfix/redis-cluster-config

or

170e8fe138317bc2be1f31c7d7a44ff613478f06

if you want to cherry-pick

**Comment by mikaelfrykholm** [comment]
I got `Oct 31 09:49:51 bankid-idp-app2 sunet-bankidp[3844870]: app_1    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisson' defined in class path resource [org/redisson/spring/starter/RedissonAutoConfiguration.class]: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception with message: cluster servers config already used!
`
This is probably due to:
https://github.com/swedenconnect/bankid-saml-idp/blob/170e8fe138317bc2be1f31c7d7a44ff613478f06/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java#L91

I hacked it to 
```
diff --git a/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java b/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java
index ef3de31..70544d4 100644
--- a/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java
+++ b/bankid-idp/src/main/java/se/swedenconnect/bankid/idp/config/session/RedisSessionConfiguration.java
@@ -88,17 +88,7 @@ public class RedisSessionConfiguration {
   }
 
   private BaseConfig<?> getConfiguration(Config config) {
-    BaseConfig<?> baseConfig = config.useSingleServer();
-    if (config.isSingleConfig()) {
-      return RedissonAddressCustomizers.singleServerSslCustomizer.apply(config.useSingleServer());
-    }
-    if (config.isClusterConfig()) {
-      return RedissonAddressCustomizers.clusterServerCustomizer.apply(config.useClusterServers());
-    }
-    if (config.isSentinelConfig()) {
-      throw new IllegalArgumentException("Sentinel Configuration is not implementend");
-    }
-    return baseConfig;
+    return RedissonAddressCustomizers.clusterServerCustomizer.apply(config.useClusterServers());
   }
 
   @Bean

```
And that made it work.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/bankid-saml-idp/pull/211. Will be part of version 1.1.1.
