### ISSUE TITLE
Override or disable the default logo in the header

### ISSUE THREAD

**Issue by theseal** [swedenconnect/bankid-saml-idp#207]
The default logo (Sweden Connect) flashes by before the SPs logo is loaded. Is it possible to disable the default header logo or at-least override it? 

Feels a little bit phishy to have a logo/image that changes during an login flow.

**Comment by theseal** [comment]
Not sure how Vue works but this might be it?
https://github.com/swedenconnect/bankid-saml-idp/blob/b1f48df46911fab2c9ce290221aea48838bf29c5/bankid-frontend/src/components/AppHeader.vue#L15C1-L16

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/210. Merged to fixbranch-1.1. Will be included in 1.1.1 release.
