### ISSUE TITLE
RedisClusterProperties throws nullpointer on empty NAT translation table

### ISSUE THREAD

**Issue by felix-hellman** [swedenconnect/bankid-saml-idp#215]
When running in cluster mode with no NAT table properties, application fails to start
`Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.natTranslation" is null`

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/swedenconnect/bankid-saml-idp/pull/216. Is now available in https://github.com/swedenconnect/bankid-saml-idp/tree/fixbranch-1.1 and will be released in 1.1.2.
