### ISSUE TITLE
Problem building docker image

### ISSUE THREAD

**Issue by mikaelfrykholm** [swedenconnect/bankid-saml-idp#226]
`mikael@terminator14 ~/s/b/build_bankid-saml-idp (fixbranch-1.1) [1]> mvn -f bankid-idp jib:dockerBuild`

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.1:dockerBuild (default-cli) on project bankid-idp: multi-platform image building not supported when pushing to Docker engine -> [Help 1]

The new multi-arch stuff seem to have broken docker builds.

**Comment by felix-hellman** [comment]
It is correct that multi-arch builds can't be published locally.

The documentation was updated regarding building locally when this was changed.

https://github.com/swedenconnect/bankid-saml-idp/blob/fixbranch-1.1/docs/development.md

```bash
export DOCKER_REPO=local
mvn clean install
mvn -f bankid-idp/bankid-idp jib:dockerBuild@local
```

**Comment by mikaelfrykholm** [comment]
Ah, I didn't catch that. Sorry for the noise. That works!
