### ISSUE TITLE
Make redis cluster read mode configurable

### ISSUE THREAD

**Issue by felix-hellman** [swedenconnect/bankid-saml-idp#228]
By default, Redisson (cluster) uses read-mode SLAVE to scale out reads.
This is not recommended for this application since spring-session (that is used for SAML) has highly coupled read/writes which can result in writing something to the master and immediately reading it from SLAVE. If SLAVE has not caught up to the master node in this short time spring session will think the session has become invalidated.

---
To fix this:
* Make read mode configurable
* Make read mode MASTER by default

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/229.
