### ISSUE TITLE
Remove ajp-conf in Jib plugin

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#232]
The jib-plugin in the POM contains `-Dtomcat.ajp.enabled=true`. This is wrong.

**Comment by felix-hellman** [comment]
You have already removed this in commit https://github.com/swedenconnect/bankid-saml-idp/commit/5a5fffa56452ec37bd712e4389f670a2fc20458f

Closing the issue.
