### ISSUE TITLE
Actuator endpoints

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#32]
Define actuator endpoints:

- health: Verifies that the system is up
    - Valid SAML metadata for all the configured clients
    - RP-certificate for all configured clients are still valid (warn when about to expire)
    - BankID API server is up
- statistics
- audit events (see separate issue about auditlogging)
- more ...

**Comment by felix-hellman** [comment]
Metrics via micrometer to enable prometheus scrape is a common setup for monitoring and should be supported during this feature.

**Comment by felix-hellman** [comment]
An effective way to check if the BankId servers are available is to add a circuitbreaker to the integration and read the state of the circuitbreaker and thus not producing any additional traffic towards their servers.

https://resilience4j.readme.io/docs/circuitbreaker

**Comment by felix-hellman** [comment]
@martin-lindstrom 
Can you add the following health indicator?
> health: Valid SAML metadata for all the configured clients
