### ISSUE TITLE
Define, implement and document Audit logging events

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#33]
We should provide audit events for:

- received authentication requests (may be done within the SAML-core lib),
- bad authentication requests (may be done within the SAML-core lib),
- initiated BankID-operations,
- successful BankID-operations,
- failed or cancelled BankID-operations,
- SAML-responses sent back to the SP (may be done within the SAML-core lib)

more?

**Comment by felix-hellman** [comment]
Closed by #60
