### ISSUE TITLE
Better hintcodes 

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#55]
https://www.bankid.com/utvecklare/guider/teknisk-integrationsguide/rp-anvaendarfall

We should have a text for RFA23 and also take action on the new v6 hintCode.

**Comment by felix-hellman** [comment]
We need to implmenet 

- Add support for hintCode=userMrtd and new text from API version 6 BankID
- Add support for checking sign or auth

**Comment by felix-hellman** [comment]
Closed by #81
