### ISSUE TITLE
Update dependency saml-idp-spring-boot-starter to latest version when released

### ISSUE THREAD

**Issue by felix-hellman** [swedenconnect/bankid-saml-idp#61]
When developing the audit logging we found some minor bugs in saml-idp-spring-boot-starter Audit Logging.
These have been fixed in the main branch. When a release has been made we should use the new version as soon as possible.

**Comment by martin-lindstrom** [comment]
Fixed in https://github.com/swedenconnect/bankid-saml-idp/pull/72
