### ISSUE TITLE
Add explanatory text for scanning QR-code

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/bankid-saml-idp#93]
I think that we need to add some helper texts for scanning the QR-code.

A good example is Kivra - https://accounts.kivra.com/bankid-auth

Also, for accessibility, we should add a frame around the QR-code (can this be done with CSS?)

**Comment by oestrogen** [comment]
@martin-lindstrom The QR code has had a border and corner since #75!

![Screenshot 2023-09-19 at 19 56 48](https://github.com/swedenconnect/bankid-saml-idp/assets/351057/081e706e-845b-4410-9c1d-b58d0b199ef5)
